phases:

#################################################
- phase: build_on_windows
#################################################
  displayName: (vsts-task-lib) Windows
  queue:
    #name: Hosted
    name: buildDevs
    demands: agent.os -equals Windows_NT

  steps:
  ################################################################################
  # vsts-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (vsts-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 5
  - powershell: |
      & "$(build.sourcesDirectory)/res/UseNode5.ps1"
    displayName: (vsts-task-lib) use node 5.10.1

  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (vsts-task-lib) node make.js test  

  # use node 6
  - task: NodeTool@0
    displayName: (vsts-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: (vsts-task-lib) node make.js test
    workingDirectory: node

  ################################################################################
  # VstsTaskSdk
  ################################################################################

  # npm install
  - task: Npm@1
    displayName: (VstsTaskSdk) npm install
    inputs:
      command: install
      workingDir: powershell

  # npm test
  - script: npm test
    displayName: (VstsTaskSdk) npm test
    workingDirectory: powershell

#################################################
- phase: build_on_linux
#################################################
  displayName: (vsts-task-lib) linux
  queue: Hosted Linux Preview

  steps:
  ################################################################################
  # vsts-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (vsts-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 5
  - task: NodeTool@0
    displayName: (vsts-task-lib) use node 5.10.1
    inputs:
      versionSpec: "5.10.1"
      
  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (vsts-task-lib) node make.js test  

  # use node 6
  - task: NodeTool@0
    displayName: (vsts-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: (vsts-task-lib) node make.js test
    workingDirectory: node

#################################################
- phase: build_on_osx
#################################################
  displayName: (vsts-task-lib) osx
  queue: Hosted Mac Internal

  steps:
  ################################################################################
  # vsts-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (vsts-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 5
  - task: NodeTool@0
    displayName: (vsts-task-lib) use node 5.10.1
    inputs:
      versionSpec: "5.10.1"
      
  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (vsts-task-lib) node make.js test  

  # use node 6
  - task: NodeTool@0
    displayName: (vsts-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: (vsts-task-lib) node make.js test
    workingDirectory: node
