trigger:
- master
- features/*
- releases/*

jobs:
#################################################
- job: windows
#################################################
  displayName: windows
  pool:
    vmImage: vs2017-win2016

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 14
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 14.11.0
    inputs:
      versionSpec: "14.11.0"

  # build/test
  - script: |
      chcp 437
      node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # build/test
  - script: |
      chcp 437
      node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node

  ################################################################################
  # VstsTaskSdk
  ################################################################################

  # npm install
  - task: Npm@1
    displayName: (VstsTaskSdk) npm install
    inputs:
      command: install
      workingDir: powershell

  # npm test
  - script: npm test
    displayName: (VstsTaskSdk) npm test
    workingDirectory: powershell

#################################################
- job: linux
#################################################
  displayName: Linux
  pool:
    vmImage: ubuntu-16.04

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 14
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 14.11.0
    inputs:
      versionSpec: "14.11.0"
      
  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # build/test
  - script: node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node

#################################################
- job: macOS
#################################################
  displayName: macOS
  pool:
    vmImage: macOS-10.15

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 14
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 14.11.0
    inputs:
      versionSpec: "14.11.0"
      
  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # build/test
  - script: node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node
