parameters:
- name: os
  type: string

steps:
- task: NodeTool@0
  displayName: use node $(nodeVersion)
  inputs:
    versionSpec: $(nodeVersion)

- task: NpmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: npm ci
  displayName: (task-lib) npm ci
  workingDirectory: node

- script: npm test
  workingDirectory: node
  displayName: (task-lib) npm test

# Only on Linux. PublishPipelineArtifact step is configured in the base template.
# See the templateContext section in the azure-pipelines.yml file

# Only on Windows. Build VstsTaskSdk for powershell 
- ${{ if eq(parameters.os, 'Windows_NT') }}:
  # Build step for .NET source code. This is needed to enable CodeQL for C# code
  - task: DotNetCoreCLI@2
    displayName: 'Build .NET project(s)'
    inputs:
      command: build
      projects: 'powershell/CompiledHelpers/VstsTaskSdk.csproj'
      arguments: '--configuration Release'

  - task: NodeTool@0
    displayName: use node $(nodeVersionForPowershell) for PowerShell SDK
    inputs:
      versionSpec: $(nodeVersionForPowershell)

  - task: NpmAuthenticate@0
    inputs:
      workingFile: .npmrc

  - script: npm ci
    displayName: (VstsTaskSdk) npm ci
    workingDirectory: powershell

  - script: npm test
    displayName: (VstsTaskSdk) npm test
    workingDirectory: powershell
