parameters:
- name: apiKeyVariable
  type: string
  default: '$(PSGalleryApiKey)'

jobs:
- job: PublishToGallery
  displayName: 'Publish PowerShell Module to Gallery'
  pool:
    vmImage: windows-2022
  variables:
    nodeVersionForPowershell: '20.x'
  steps:
  - checkout: self
    displayName: 'Checkout source code'

  # First build and test the module
  - template: /ci/powershell/steps.yml@self
    parameters:
      runTests: true    # Always test before publishing
      os: Windows_NT    # Specify OS for proper .NET build

  # Then publish to PowerShell Gallery
  - powershell: |
      Install-Module -Name Microsoft.PowerShell.PSResourceGet -Force -Verbose
    displayName: 'Install PowerShell Gallery publish tools'

  - powershell: |
      $publishOptions = @{
          Path       = '.\_build\VstsTaskSdk'
          ApiKey     = $env:API_KEY
          Repository = 'PSGallery'
          Verbose    = $true
      }
      Publish-PSResource @publishOptions
    displayName: 'Publish to PowerShell Gallery'
    workingDirectory: powershell
    env:
      API_KEY: ${{ parameters.apiKeyVariable }}

  - task: PublishPipelineArtifact@1
    displayName: 'Publish built module as artifact'
    inputs:
      targetPath: 'powershell/_build'
      artifact: 'VstsTaskSdk-Published'
      publishLocation: 'pipeline'
    condition: succeededOrFailed()