# Release pipeline for publishing packages
# This pipeline should be triggered manually for publishing releases

trigger: none # No CI trigger - manual trigger only
pr: none # No PR trigger

variables:
- group: npm-tokens
- group: powershell-gallery-secrets
- group: TasksAndAgentEsrpSigning
- name: nodeVersion
  value: '16.13.0'
- name: nodeVersionForPowershell
  value: '20.x'

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      skipBuildTagsForGitHubPullRequests: true
    sdl:
      baseline:
        baselineSet: default
        baselineFile: $(Build.SourcesDirectory)/.gdn/.gdnbaselines
      sourceAnalysisPool:
        name: 1ES-ABTT-Shared-Pool
        image: abtt-windows-2022
        os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: PublishPackages
      displayName: 'Publish Packages'
      jobs:
      # Publish Node.js package to npm
      - template: /ci/node/publish-job.yml@self
        parameters:
          npmToken: $(npm-automation.token)

      # Publish PowerShell module to PowerShell Gallery (with signing)
      - template: /ci/powershell/publish-job.yml@self
        parameters:
          apiKeyVariable: $(PSGalleryApiKey)
          enableSigning: true
